### ISSUE TITLE
5T examples

### ISSUE THREAD

**Issue by muthukumar2k3** [molmod/tamkin#2]
I think, 5T examples do not work.
Can you plese check. 
Couldn't even load them onto Gaussview.

**Comment by tovrstra** [comment]
Sorry for the late reply. It seems to work for me. Can you describe the problem in more detail?

It is normal that the `fchk` files cannot be loaded into Gaussview. They have been stripped to only contain the information relevant for TAMkin, which may not be enough for GaussView. (I'm not even sure if GaussView can load formatted checkpoint files as I don't use this program.)

**Comment by tovrstra** [comment]
Closing by lack of reply. If you want to get back in touch, feel free to open another issue.
