### ISSUE TITLE
Update installation instructions (Ubuntu/Python 3)

### ISSUE THREAD

**Issue by mefuller** [molmod/tamkin#26]
For a clean install on a fully updated Ubuntu 20.04 LTS (12 June 2020), recommend the installation instructions be updated as follows (https://molmod.github.io/tamkin/tutorial/install.html):

External dependencies:
`sudo apt install python3 python3-numpy python3-scipy python3-matplotlib python3-nose python3-pip cython3`
As currently written, pip and cython are not installed automatically, leading to errors when attempting to install tamkin with pip.
Also, as currently written with `python`and not `python3`, clean installs default to python2 and prompt to install `python-is-python2` which sets system python to 2.x: It is my suggestion that the installation instructions be written for python3 to avoid setting the default to python 2, which has reached end-of-life. 
EDIT: I am also recommending replacing `apt-get` by `apt` as this is a newer and preferred implementation for command-line package management in Ubuntu and Debian.

Installation:
It is not be necessary to install numpy and nosetests with pip when installed systemwide under external dependencies.

**Comment by tovrstra** [comment]
Fixed in #30
