### ISSUE TITLE
nosetest fail: timer.py

### ISSUE THREAD

**Issue by mefuller** [molmod/tamkin#27]
On a clean install of tamkin under python3.8 on Ubuntu 20.04 LTS, the nosetest for timer.py fails:
EDIT: this issue was verified on Fedora 32 with python3.8
```
======================================================================
ERROR: test_timer (tamkin.test.test_timer.TimerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fuller/.local/lib/python3.8/site-packages/tamkin/test/test_timer.py", line 53, in test_timer
    timer.sample("start")
  File "/home/fuller/.local/lib/python3.8/site-packages/tamkin/timer.py", line 67, in sample
    self.cpu_times.append(time.clock())
AttributeError: module 'time' has no attribute 'clock'

----------------------------------------------------------------------
Ran 126 tests in 22.446s

FAILED (errors=1)
```

According to release information for python 3.8 (https://docs.python.org/3/whatsnew/3.8.html):

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

**Comment by tovrstra** [comment]
Fixedin #31.
