### ISSUE TITLE
Update installation instructions (Fedora/Python 3)

### ISSUE THREAD

**Issue by mefuller** [molmod/tamkin#28]
As in the associated issue with Ubuntu (https://github.com/molmod/tamkin/issues/26), the installation instructions for Fedora should be updated (tested on updated Fedora 32, 12 June 2020):

Recommend the installation instructions be updated as follows (https://molmod.github.io/tamkin/tutorial/install.html):

External dependencies:
`sudo dnf install python3 python3-numpy python3-scipy python3-matplotlib python3-nose python3-Cython`
As currently written, Cython are not installed automatically, leading to errors when attempting to install tamkin with pip.
Also, as currently written, `scipy` returns an error ("not found") and `numpy` prompts for install of `python2-numpy`
Also here it is my recommendation that the installation instructions be written for python3 to avoid python2, which has reached end-of-life.

Installation:
It is not be necessary to install numpy and nosetests with pip when installed systemwide under external dependencies.

**Comment by tovrstra** [comment]
Fixed in #30
